on: [push, pull_request]

name: R-shield

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip shield')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '3.6', args: "--no-manual"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_github('yonicd/shield')
          shield::install_remotes(shield::create_map())
          remotes::install_local(force = TRUE, upgrade = TRUE)
          remotes::install_cran('rcmdcheck')
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: slackreprex trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_PAT}}
          repository: yonicd/slackreprex
          event-type: push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
